version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    tty: true
    volumes:
      - ./src:/go/src
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=food_manage
      - MYSQL_HOST=mysql
      - MYSQL_USER=narita
      - MYSQL_PASSWORD=narita1005
      - MYSQL_ROOT_PASSWORD=narita1005
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./mysql_data/mysql:/var/lib/mysql"
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"
